# CLASE CIENCIA DE DATOS | 19-05 | NUMPY    
<hr style="border: 0.5px solid black">

In [1]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

In [9]:
a=np.arange(2,12)
print(a)

print("ndim: ", a.ndim)
print("shape:", a.shape)
print("size: ", a.size)

[ 2  3  4  5  6  7  8  9 10 11]
ndim:  1
shape: (10,)
size:  10


## TEMAS VARIOS
* DATA TYPES
* DIMENSIONES
* ARANGE
* NUMEROS ALEATORIOS - RANDOM
* INDEXING
* SLICING
* JOIN
* SORT

# <span style="color:blue">QUE ES UN ARRAY</span>

* **El array (o ndarray) es la estructura que permite acelerar las operaciones matemáticas en Python, sin
la necesidad de recurrir a bucles para operar con todos sus elementos, lo que se llama vectorización.**        


* **Es una estructura multidimensional, por lo que permite representar vectores,     
matrices o arreglos de más dimensiones.**

## NUMPY DATATYPES

* strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
* integer - used to represent integer numbers. e.g. -1, -2, -3
* float - used to represent real numbers. e.g. 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## CREAR ARRAY - DIMENSIONES

In [65]:
#arreglo 0 d
arr0=np.array((10))
arr0.ndim

0

In [66]:
#crear un array de 1 dimensión
arr1=np.array([1,2,3,4,5])

shape=arr1.shape #me devuelve filas/columnas
ndim=arr1.ndim  #me devuelve la dimension
size=arr1.size
dtype=arr1.dtype
print(f"Cantidad de filas y columnas: {shape}. Dimensión: {ndim}. Cantidad de elementos: {size}. Tipo de datos: {dtype}")

Cantidad de filas y columnas: (5,). Dimensión: 1. Cantidad de elementos: 5. Tipo de datos: int32


In [4]:
#crear un array de 1 lista 
lista=[1,2,3,4,5,6,7]
arr2=np.array(lista)
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
#crear un array de 2 dim
arr3=np.array([[1,2,3],[4,5,6]])
arr3.ndim
print("Cantidad de filas y col",arr3.shape,"Dimensión:",arr3.ndim," Cantidad de elementos: ",arr3.size,"Tipo de datos: ",arr3.dtype)

Cantidad de filas y col (2, 3) Dimensión: 2  Cantidad de elementos:  6 Tipo de datos:  int32


In [6]:
#crear arreglo de dos dimensiones
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
arreglo3=np.array([matrix, matrix])
print(arreglo3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
mat3d=np.array([[[2,4,6],[4,8,12]],[[2,4,6],[4,8,12]]])
mat3d.ndim

3

In [9]:
#argumento para la dimension
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


## **RANGO DE VALORES - ARANGE**

In [10]:
a=np.arange(1,16,2)
a
#si agrego 3er paso le indico cada cuanto aumenta

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [4]:
zz=np.arange(1,11)
print(zz)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
b=np.arange(0,100,25)
b

array([ 0, 25, 50, 75])

# <span style="color:blue">RANDOM - Numeros aleatorios con NumPy</span>

## RANDINT - ENTEROS

In [12]:
# generar arreglo con nros enteros valor inicial,valor final, tamaño
x = np.random.randint(0,100,size=25)
print(x)


[83 22 18 31 56 39 21  3 84 17 66  7 51 22 14 41 15 80 26 15 87 64 79 23
 59]


## RAND - ENTRE 0 Y 1 FLOAT

In [13]:
#nros aleatorios entre 0 y 1
b=np.random.rand(10)
print(b)

[0.66969382 0.13386712 0.05157755 0.19916768 0.93853692 0.41592704
 0.50140864 0.05542528 0.87291059 0.32867217]


In [14]:
arr4=np.array([arr3, arr3])
print("Cantidad de filas y col",arr4.shape,"Dimensión:",arr4.ndim," Cantidad de elementos: ",arr4.size,"Tipo de datos: ",arr4.dtype)

Cantidad de filas y col (2, 2, 3) Dimensión: 3  Cantidad de elementos:  12 Tipo de datos:  int32


## LINSPACE - UNIFORMEMENTE ESPACIADOS

In [5]:
#Crear un arreglo con valores uniformemente espaciado
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

arreglo=np.linspace(15, 20, 7)
arreglo

array([15.        , 15.83333333, 16.66666667, 17.5       , 18.33333333,
       19.16666667, 20.        ])

## FULL - ARREGLO CON MISMO NUM

In [3]:
#creando un arreglo con un mismo numero
#numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
arreglo=np.full((3,3),6)
print(arreglo)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [17]:
arreglo=np.linspace(15, 20, 7)
print(arreglo)

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


## ZEROS - ARREGLO CON CEROS

In [18]:
# creando un arreglo con 0
arreglo=np.zeros((3,5))
print(arreglo)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## UNIFORM - PERMITE INDICAR EL RANGO

In [19]:
#uniform permite indicar el rango, a diferencia de rand q solo va de 0 a 1
np.random.uniform(1.5, 2.0, size=50)

array([1.94104763, 1.76572354, 1.80446399, 1.8320874 , 1.70734663,
       1.84619991, 1.63747947, 1.78471249, 1.99486215, 1.726998  ,
       1.71205764, 1.77364654, 1.70509582, 1.89914899, 1.89959019,
       1.99301846, 1.67367461, 1.77434737, 1.78497231, 1.51004979,
       1.63125443, 1.6262942 , 1.85753703, 1.66403209, 1.96073479,
       1.8647908 , 1.84163293, 1.99612988, 1.58769396, 1.64617136,
       1.50795036, 1.69191685, 1.65624663, 1.88524562, 1.94465995,
       1.83841993, 1.73646067, 1.71470175, 1.61366327, 1.6270595 ,
       1.82025247, 1.53130505, 1.63686083, 1.63007001, 1.51668323,
       1.9218063 , 1.53299002, 1.9569441 , 1.79586105, 1.96958207])

In [20]:
x = np.random.rand(3, 5)

print(x)


[[0.39662716 0.18554511 0.92126084 0.77972009 0.19364159]
 [0.06617466 0.43609083 0.83218624 0.12419027 0.49760563]
 [0.13685252 0.99899294 0.16125874 0.64260169 0.80373148]]


## CHOICE - QUE VALORES PUEDE CONTENER

In [21]:
#selecciona al azar de una lista que le doy
arrejemplo=np.array([1,2,3,4,5])
random_elements=np.random.choice(arrejemplo,size=(3,4))
random_elements

array([[1, 5, 2, 1],
       [1, 2, 1, 3],
       [4, 3, 1, 2]])

## EJERCICIO 02-06 | CHOICE

In [22]:
#Ejercicio crear una arreglo con los primeros 11 nros primos, 
#y luego usarlo como insumo para generar una matriz de 4 filas y 7 columnas

numeros_primos=np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

random_choice=np.random.choice(numeros_primos,size=(4,7))

print(random_choice,"\nTamaño: ",random_choice.shape)

[[23  7  3  5 29  3 13]
 [17 29 29 19  5 17 13]
 [13 19 29 29 19 13  3]
 [13  2 23 13 29  7 23]] 
Tamaño:  (4, 7)


In [23]:
arrejemplo2=np.array(["a","b","c","d","e"])
random_elements2=np.random.choice(arrejemplo2,size=(3,4))
random_elements2

array([['a', 'b', 'e', 'c'],
       ['d', 'b', 'b', 'd'],
       ['b', 'e', 'a', 'd']], dtype='<U1')

In [24]:
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 5 7 3]
 [7 7 9 3 7]
 [3 7 5 3 7]]


In [25]:
x = np.random.choice([3, 5, 7, 9])

print(x)

3


## INDEXING

In [26]:
mat2d=np.array([[4,5,6],[7,8,9]])
mat2d

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
#acceder a uh elemento por fila y col
mat2d[1,0]

7

In [28]:
array=np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
array[:,:2]
#filtro todas la filas y columnas de la cero a la 1

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [30]:
array[2,:]
#filtro ultima fila completa

array([11, 12, 13, 14, 15])

#  <span style="color:blue">NUMPY SLICING</span> 

* Slicing in python means taking elements from one given index to another given index.

* We pass slice instead of index like this: [start:end].    

* We can also define the step, like this:[start:end:step] 

In [31]:
import numpy as np
z=np.random.randint(0,100,size=20)
z[0:5:2]

array([96, 27,  1])

In [32]:
z

array([96, 25, 27, 21,  1, 89, 17, 33,  4, 75, 39,  0, 25, 68, 25,  9, 54,
       27,  0, 59])

In [33]:
#slice negativo
z[-3:]

array([27,  0, 59])

In [34]:
arr1[0:4:2]

array([1, 3])

In [35]:
are= np.arange(1,10).reshape(3,3)
are[0,0:3]


array([1, 2, 3])

In [36]:
are

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#slice en mat 2d
arrz= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arrz[1, 1:4])

[7 8 9]


In [38]:
#slice en mat 2d, elegimos de ambos elementos, el indice 1 de cada uno
print(arrz[0:2, 1])

[2 7]


In [39]:
#slice en mat 2d, elegimos de ambos elementos, indices de 0 a 4 no incluido de cada uno
print(arrz[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
# Creamos un array de 10 elementos del 0 al 9
ar= np.arange(10)

# Seleccionamos elementos con un paso de 2
resultado = ar[::2]

print(resultado)  # Salida: [0 2 4 6 8]

[0 2 4 6 8]


## **FILTRAR CON CONDICIONES**

In [41]:
a[a>10]

array([11, 13, 15])

In [42]:
a[a>1]

array([ 3,  5,  7,  9, 11, 13, 15])

## OPERACIONES

In [43]:
a=np.array([1,2,3,4,5])

b=a**3

print(b)

[  1   8  27  64 125]


In [44]:
#podemos operar vectorialmente, siempre que sean de las mismos tamaños
c=np.array([6,7,8,9,10])

d=a+c

print(d)

[ 7  9 11 13 15]


## EJERCICIO. Crear un matrix de 4 filas y 5 columnas , con el mismo valor 5.

In [45]:
arreglo45=np.full(20,5).reshape(4,5)
arreglo45

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## EJERCICIO. ARREGLO MATRIZ 5 fila y 3 col , valores aleatorios entre 5 y 6

In [46]:
ejercicio= np.random.randint(5,7,size=(5,3))
ejercicio


array([[5, 6, 5],
       [5, 6, 5],
       [5, 6, 5],
       [5, 5, 5],
       [5, 5, 6]])

In [47]:
np.random.rand(5,6)

array([[0.5174388 , 0.46781146, 0.07488056, 0.65776631, 0.31076056,
        0.66984574],
       [0.97485643, 0.47672448, 0.87377916, 0.73018016, 0.61422522,
        0.93767711],
       [0.56010666, 0.06346555, 0.07346163, 0.80329795, 0.55052963,
        0.37344715],
       [0.54477486, 0.87096709, 0.67867622, 0.03057684, 0.95484335,
        0.37424886],
       [0.1704073 , 0.97426829, 0.11153942, 0.34334659, 0.02016762,
        0.69104067]])

## EJERCICIO:     
**Crear un arreglo denominado altura de tamaño 50. Debe de generar aleatoriamente las alturas entre 1.5m y 2m.
Crear un arreglo denominado peso de tamaño 50. Debe de generar aleatoriamente los pesos entre 50kg y 100kg.
Calcular el índice de masa corporal en un tercer arreglo.**

In [48]:
altura = np.random.uniform(1.5, 2.0, size=50)

peso = np.random.uniform(50, 100, size=50)

imc = peso / (altura**2) 
imc

array([26.86238436, 19.65928715, 24.54722521, 29.97519448, 25.43841958,
       16.76140566, 19.04577135, 29.40804855, 37.6456131 , 24.3542559 ,
       28.66510598, 25.06805254, 13.8389622 , 18.67395546, 29.81710867,
       30.73291585, 20.64376342, 27.1105808 , 14.5997875 , 16.10644175,
       23.84059729, 20.73990142, 25.91417566, 27.97512717, 27.82151961,
       29.19625804, 22.18269096, 29.87663966, 27.73808231, 25.13823522,
       24.99833214, 27.5922204 , 26.41014571, 26.51295968, 29.84088555,
       23.99709487, 19.95226134, 15.89075248, 41.09518609, 27.37611556,
       30.2513357 , 23.10370444, 22.65445175, 23.72429981, 34.17005368,
       21.45855904, 35.42131371, 30.54360694, 21.27685408, 25.40262714])

## Ejercicio matriz de 3 filas y 5 columnas num de 1 al 15

In [49]:
arr5=np.arange(1,16)
arr6=arr5.reshape(3,5)
#arr5=np.arange(1,16).reshape(3,5)

In [50]:
z=np.array([1,2,3])
x=z
z[0]=55
print(x)
print(z)

[55  2  3]
[55  2  3]


#  <span style="color:blue">NUMPY ITERAR ARRAYS</span> 

In [51]:
#ARRAY 3D
ar2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

for x in ar2d:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [52]:
#ARRAY 3D
ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in ar:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**La función nditer() es una función de ayuda que se puede usar desde iteraciones muy básicas hasta muy avanzadas. Resuelve algunos problemas básicos que enfrentamos en la iteración, analicémoslo con ejemplos.**

In [53]:
#NDITER
arr55 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr55):
  print(x)

1
2
3
4
5
6
7
8


**NDENUMERATE: Enumeración significa mencionar el número de secuencia de algo uno por uno.
A veces requerimos el índice correspondiente del elemento durante la iteración, el método ndenumerate() se puede usar para esos casos de uso.**

In [54]:
ar44 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(ar44):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#  <span style="color:blue">JOIN EN NUMPY</span> 

**JOIN significa poner el contenido de dos o más matrices en una sola matriz.**

**En SQL unimos tablas en base a una clave, mientras que en NumPy unimos matrices por ejes.**

**Pasamos una secuencia de arreglos que queremos unir a la función concatenar(), junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.**

In [5]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [9]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
arrb = np.concatenate((arr1, arr2), axis=0)

print(arrb)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## STACK

El apilamiento es lo mismo que la concatenación, la única diferencia es que el apilamiento se realiza a lo largo de un nuevo eje.

Podemos concatenar dos matrices 1-D a lo largo del segundo eje, lo que daría como resultado colocarlas una sobre la otra, es decir. apilado.

Pasamos una secuencia de arreglos que queremos unir al método stack() junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.

In [57]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [58]:
are = np.array([1, 2, 3])

are2 = np.array([4, 5, 6])

arre = np.stack((are, are2),axis=1)

print(arre)

[[1 4]
 [2 5]
 [3 6]]


##  <span style="color:blue">SORTING ARRAYS</span> 

**Eje a lo largo del cual ordenar. Si es Ninguno, la matriz se aplana antes de ordenar. El valor predeterminado es -1, que ordena a lo largo del último eje.**

In [59]:
#ordenar  numpy.sort(a, axis=-1, kind=None, order=None)

sortarray=np.random.randint(2,21,size=(10))
sortarray2=np.sort(sortarray)

print(sortarray)
print("\n",sortarray2)

[16  8 20 17 20  9 18 20  7  7]

 [ 7  7  8  9 16 17 18 20 20 20]


In [60]:
#ordenar, al usar xis=0 me ordena todos los elementos mas alla que sean de filas diferentes, sino ordenaria 
#solo cada elemento por fila de manera indepte

sortarray3=np.random.randint(2,21,size=(10,2))
sortarray4=np.sort(sortarray3,axis=0)

print(sortarray3)
print("\n",sortarray4)

[[ 2  5]
 [ 5 16]
 [ 6  7]
 [18  7]
 [ 2 10]
 [ 9 12]
 [ 3  5]
 [ 2  9]
 [17 16]
 [17 19]]

 [[ 2  5]
 [ 2  5]
 [ 2  7]
 [ 3  7]
 [ 5  9]
 [ 6 10]
 [ 9 12]
 [17 16]
 [17 16]
 [18 19]]


In [61]:
#ordenar, al no usar axis=0 sino ordenaria solo cada elemento de cada fila de manera indepte

sortarray5=np.random.randint(2,21,size=(10,2))
sortarray6=np.sort(sortarray5,axis=0)

print(sortarray5)
print("\n",sortarray6)

[[18  4]
 [15 15]
 [14  5]
 [20 13]
 [19 16]
 [18 17]
 [ 6 17]
 [ 9  2]
 [ 5  4]
 [10  9]]

 [[ 5  2]
 [ 6  4]
 [ 9  4]
 [10  5]
 [14  9]
 [15 13]
 [18 15]
 [18 16]
 [19 17]
 [20 17]]


In [62]:
#ordenar, al usar axis None aplana al arreglo
sortarray7=np.random.randint(2,21,size=(10,2))
sortarray8=np.sort(sortarray7,axis=None)

print(sortarray7)
print("\n",sortarray8)

[[17  9]
 [14  4]
 [17 11]
 [18 17]
 [18  7]
 [15  7]
 [18 12]
 [ 3 17]
 [ 4  7]
 [12 12]]

 [ 3  4  4  7  7  7  9 11 12 12 12 14 15 17 17 17 17 18 18 18]


## OPERACIONES MAT

In [63]:
arraymat=np.array([1,2,3,4])
arraymat2=np.array([1,2,3,4])
print(arraymat+arraymat2)
print("\n",arraymat*2)
print("\n",arraymat+10)
print("\n",arraymat/2)

[2 4 6 8]

 [2 4 6 8]

 [11 12 13 14]

 [0.5 1.  1.5 2. ]


## COMPARACIONES

In [64]:
arraymat<2

array([ True, False, False, False])