# CLASE CIENCIA DE DATOS | 16-06 | NUMPY    
<hr style="border: 0.5px solid black">

In [1]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

## TEMAS VARIOS
* TRABAJAR CON TXT
* EJERCICIO
* MATPLOTLIB

##  <span style="color:blue">TRABAJAR CON TXT</span> 

In [2]:
#creamos un arreglo con aleatorios enteros de 1 al 10, se guarda en arreglo de 4x5
a=np.random.randint(1,11,(4,5))
print(a)

[[ 6  9  9  5  3]
 [ 4  3  2  9 10]
 [ 6 10 10  4  6]
 [ 2  4  4  6  6]]


In [3]:
#numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
#[source]
np.savetxt('datos_sala2.txt',a)

In [6]:
#numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)[source]

b=np.loadtxt('datos_sala2.txt',delimiter=' ',dtype='int')
print(b)

[[ 7  4  9  8  2]
 [ 1  1  3  7  1]
 [ 3  9  4  2  3]
 [ 2 10  1 10  8]]


In [4]:
#leer un txt
nombres=np.loadtxt('nombres.txt',dtype=str)
print(nombres)

['juan' 'marcelo' 'juana' 'marcela']


In [10]:
#genfromtxt ( fname , dtype=<class 'float'> , comments='#' , delimiter=Ninguno , skip_header=0 , skip_footer=0 , convertidores=Ninguno , valores_faltantes=Ninguno , valores_de_relleno=Ninguno , usecols=Ninguno , nombres=Ninguno , includelist=Ninguno , deletechars=" !#$%&'()*+ , -./:;<=>?@[\\]^{|}~" , replace_space='_' , autostrip=False , mayúsculas y minúsculas=Verdadero ,, desempaquetar=Ninguno , usemask=False , loose=True , invalid_raise=True , max_rows=Ninguno , codificación='bytes' , * , ndmin=0 , like=Ninguno )[fuente]

nombres2=np.genfromtxt('nombres.txt',dtype='str',delimiter=' ')
print(nombres2)
print(nombres2.dtype)

['juan' 'marcelo' 'juana' 'marcela']
<U7


In [21]:
#EXPORTAND TXT CON FLOAT Y SEPARADOR POR COMAS, LUEGO LEERLO

nuevoarr=np.random.uniform(40,60,size=9).reshape(3,3)
print(nuevoarr)
np.savetxt('datos_uniform.txt',nuevoarr,delimiter=',')
arrunif=np.loadtxt('datos_uniform.txt',delimiter=',',dtype=float)
print(arrunif)


[[42.88830504 54.46817186 51.86746179]
 [51.01592606 55.09114256 40.62008719]
 [48.60856694 52.0317953  55.7269691 ]]
[[42.88830504 54.46817186 51.86746179]
 [51.01592606 55.09114256 40.62008719]
 [48.60856694 52.0317953  55.7269691 ]]


In [22]:
#COLUMN STACK
# Arreglos de ejemplo
arreglo1 = np.array([1, 2, 3])
arreglo2 = np.array([4, 5, 6])

# Utilizar np.column_stack para combinar los arreglos
resultado = np.column_stack((arreglo1, arreglo2))

print(resultado)

[[1 4]
 [2 5]
 [3 6]]


## EJERCICIO

In [32]:
#crear archivo de texto dias_semana que contenga los dias y leerlo
# crear txt con min de la semana y leerlos y mostrarlas con el dia corresp. Por ej lunes 12° martes 4°

# Crear un arreglo de temperaturas mínimas
temperaturas = np.array([5, 4, 8, 3, 2, 1, 7])

# Crear un arreglo de días correspondientes
dias = np.array(["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"])

# Guardar los datos en un archivo de texto
#"%s", que indica que los datos son cadenas de texto."%d" para enteros o "%f" para float.
np.savetxt("temperaturas.txt", np.column_stack((dias, temperaturas)), fmt="%s", delimiter=" ")

# Leer los datos del archivo de texto
datos = np.genfromtxt("temperaturas.txt", dtype=str)

# Mostrar las temperaturas con los días correspondientes
for dato in datos:
    dia = dato[0]
    temperatura = dato[1]
    print(f"{dia}: {temperatura}°")

lunes: 5°
martes: 4°
miércoles: 8°
jueves: 3°
viernes: 2°
sábado: 1°
domingo: 7°


In [36]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr3=np.column_stack((arr1,arr2))
print(arr3)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
