# CLASE CIENCIA DE DATOS | 12-05 | NUMPY

**IMPORTAMOS LAS LIBRERÍAS**

In [1]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

# QUE ES UN ARRAY

* **El array (o ndarray) es la estructura que permite acelerar las operaciones matemáticas en Python, sin
la necesidad de recurrir a bucles para operar con todos sus elementos, lo que se llama vectorización.**        


* **Es una estructura multidimensional, por lo que permite representar vectores,     
matrices o arreglos de más dimensiones.**

In [2]:
#crear un array de 1 dimensión
arr1=np.array([1,2,3,4,5])

shape=arr1.shape #me devuelve filas/columnas
ndim=arr1.ndim  #me devuelve la dimension
size=arr1.size
dtype=arr1.dtype
print(f"Cantidad de filas y columnas: {shape}. Dimensión: {ndim}. Cantidad de elementos: {size}. Tipo de datos: {dtype}")

Cantidad de filas y columnas: (5,). Dimensión: 1. Cantidad de elementos: 5. Tipo de datos: int32


In [3]:
#crear un array de 1 lista 
lista=[1,2,3,4,5,6,7]
arr2=np.array(lista)
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
#crear un array de 2 dim
arr3=np.array([[1,2,3],[4,5,6]])
arr3.ndim
print("Cantidad de filas y col",arr3.shape,"Dimensión:",arr3.ndim," Cantidad de elementos: ",arr3.size,"Tipo de datos: ",arr3.dtype)

Cantidad de filas y col (2, 3) Dimensión: 2  Cantidad de elementos:  6 Tipo de datos:  int32


In [5]:
#crear arreglo de dos dimensiones
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
arreglo3=np.array([matrix, matrix])
print(arreglo3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## **RANGO DE VALORES - ARANGE**

In [7]:
a=np.arange(1,16,2)
a
#si agrego 3er paso le indico cada cuanto aumenta

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [8]:
b=np.arange(0,100,25)
b

array([ 0, 25, 50, 75])

## Numeros aleatorios con NumPy

In [9]:
# generar arreglo con nros enteros valor inicial,valor final, tamaño
x = np.random.randint(0,100,size=25)
print(x)


[48 53  9  4 49 73 67 79 20 74 96 74 97 51 79 44 90 40  8 59 82 45  8 94
 76]


In [10]:
#nros aleatorios entre 0 y 1
b=np.random.rand(100)
print(b)

[9.71803747e-01 5.96977519e-01 8.79529299e-02 9.19382480e-01
 5.59267325e-01 2.00911058e-01 4.03802910e-01 1.59151504e-01
 2.68779952e-01 4.35494120e-01 9.65566047e-01 1.87115295e-02
 3.22347712e-01 9.00876896e-01 1.64867973e-01 2.41741139e-01
 4.42511681e-01 8.84896372e-01 7.97654710e-01 3.36802743e-02
 2.90448404e-01 9.66833781e-01 5.54353049e-01 7.19071579e-01
 2.65379281e-01 1.95266613e-01 2.57917964e-01 6.08573816e-01
 3.03960800e-01 1.80986354e-01 5.18422123e-01 3.94792259e-01
 2.97954098e-01 7.15451810e-01 4.59967401e-01 2.90374314e-04
 9.47903080e-01 6.74118886e-01 3.78396145e-01 4.95815557e-01
 3.52560581e-01 8.96194767e-02 9.22421439e-01 5.00809241e-01
 6.66695806e-01 9.67967800e-01 6.83058768e-01 4.55958043e-01
 5.08070899e-01 6.47980426e-01 5.67429602e-01 8.74215593e-01
 2.17513793e-01 5.51122848e-01 9.60671171e-01 2.01468202e-01
 3.68508484e-01 5.07396543e-01 4.71280607e-01 3.82876767e-01
 7.43205877e-02 8.69250980e-01 4.75988603e-02 6.08361922e-01
 9.31764161e-01 1.668998

In [11]:
arr4=np.array([arr3, arr3])
print("Cantidad de filas y col",arr4.shape,"Dimensión:",arr4.ndim," Cantidad de elementos: ",arr4.size,"Tipo de datos: ",arr4.dtype)

Cantidad de filas y col (2, 2, 3) Dimensión: 3  Cantidad de elementos:  12 Tipo de datos:  int32


In [12]:
#Crear un arreglo con valores uniformemente espaciados
arreglo=np.linspace(15, 20, 7)
print(arreglo)

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


In [13]:
#creando un arreglo con un mismo numero
arreglo=np.full(10,6)
print(arreglo)

[6 6 6 6 6 6 6 6 6 6]


In [14]:
arreglo=np.linspace(15, 20, 7)
print(arreglo)

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


In [15]:
# creando un arreglo con 0
arreglo=np.zeros((3,5))
print(arreglo)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#uniform permite indicar el rango, a diferencia de rand q solo va de 0 a 1
np.random.uniform(1.5, 2.0, size=50)

array([1.5316511 , 1.87610794, 1.89010349, 1.96908589, 1.87937634,
       1.92773289, 1.86494268, 1.87003752, 1.73742862, 1.89824738,
       1.76457907, 1.75209419, 1.82700823, 1.74927722, 1.85288105,
       1.50417725, 1.85857215, 1.81115413, 1.88515258, 1.78660437,
       1.69868805, 1.71004979, 1.9737779 , 1.92525113, 1.74914381,
       1.9103642 , 1.99174525, 1.75461518, 1.60764304, 1.64076474,
       1.5502405 , 1.58621961, 1.60796053, 1.9537332 , 1.55222765,
       1.76203332, 1.83189058, 1.61599596, 1.8058235 , 1.78407367,
       1.56903065, 1.8721075 , 1.91049267, 1.89621162, 1.54903045,
       1.98624161, 1.53940492, 1.88829032, 1.92085194, 1.60932657])

## EJERCICIO. Crear un matrix de 4 filas y 5 columnas , lleno completamente del mismo valor 5.

In [17]:
arreglo45=np.full(20,5).reshape(4,5)
arreglo45

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## EJERCICIO. ARREGLO MATRIZ 5 fila y 3 col , valores aleatorios entre 5 y 6

In [18]:
ejercicio= np.random.randint(5,7,size=(5,3))
ejercicio


array([[6, 6, 5],
       [5, 6, 5],
       [5, 6, 5],
       [6, 5, 5],
       [6, 5, 5]])

In [19]:
np.random.rand(5,6)

array([[0.50553484, 0.847839  , 0.43401405, 0.58109524, 0.82865207,
        0.9911381 ],
       [0.61943966, 0.90706752, 0.21568205, 0.27295826, 0.24028302,
        0.76666803],
       [0.65491113, 0.65991007, 0.8427653 , 0.40679062, 0.53730716,
        0.01759307],
       [0.75129052, 0.08818674, 0.05537198, 0.00880988, 0.79354499,
        0.2902458 ],
       [0.60604408, 0.85990268, 0.6395433 , 0.14351444, 0.49538089,
        0.10629671]])

## EJERCICIO:     
**Crear un arreglo denominado altura de tamaño 50. Debe de generar aleatoriamente las alturas entre 1.5m y 2m.
Crear un arreglo denominado peso de tamaño 50. Debe de generar aleatoriamente los pesos entre 50kg y 100kg.
Calcular el índice de masa corporal en un tercer arreglo.**

In [20]:
altura = np.random.uniform(1.5, 2.0, size=50)

peso = np.random.uniform(50, 100, size=50)

imc = peso / (altura**2) 
imc

array([22.47586758, 41.39055972, 17.02700432, 33.99851297, 32.2838192 ,
       39.50065541, 18.93245363, 22.10077574, 30.23945729, 27.87413182,
       13.50848028, 22.20599924, 39.30627393, 15.74617687, 33.2130066 ,
       30.44649599, 18.03875102, 26.41656618, 17.21026273, 16.39114513,
       26.2049907 , 18.86408481, 23.89591762, 28.77989582, 19.51901464,
       32.42480041, 16.4906873 , 18.48210596, 35.96776046, 15.84088166,
       20.76021989, 20.99547544, 20.67088422, 31.14055215, 41.04608681,
       14.44512053, 30.20534232, 27.72470016, 14.63501357, 18.10345713,
       22.82128855, 32.00156416, 30.61843012, 26.89629722, 30.49016092,
       31.76835124, 19.46546561, 23.28005592, 16.23475038, 17.46503859])

## Ejercicio matriz de 3 filas y 5 columnas num de 1 al 15

In [21]:
arr5=np.arange(1,16)
arr6=arr5.reshape(3,5)
#arr5=np.arange(1,16).reshape(3,5)

## **INDEXING**

In [22]:
a[3]

7

In [23]:
array=np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
array[:,:2]
#filtro todas la filas y columnas de la cero a la 1

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [25]:
array[2,:]
#filtro ultima fila completa

array([11, 12, 13, 14, 15])

## **FILTRAR CON CONDICIONES**

In [26]:
a[a>10]

array([11, 13, 15])

## Operaciones

In [27]:
a=np.array([1,2,3,4,5])

b=a**3

print(b)

[  1   8  27  64 125]


In [28]:
#podemos operar vectorialmente, siempre que sean de las mismos tamaños
c=np.array([6,7,8,9,10])

d=a+c

print(d)

[ 7  9 11 13 15]
