# CLASE CIENCIA DE DATOS | 09-06 | NUMPY    
<hr style="border: 0.5px solid black">

## **IMPORTAMOS LAS LIBRERÍAS**

In [3]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

#https://deepnote.com/@anthonymanotoa/Tutorial-de-NumPy-en-Espanol-180f7d51-b297-4aea-b61e-34ef867ca6fb

In [4]:

a = np.random.randint(0,100,size=25)
print(a)
print(np.mean(a))


[47 90 28 66 57 65 38 68 32 48  0 18 86 27 32 45 26  3 78  4  7 54 68 92
 74]
46.12


In [5]:

peso=np.array([56,78,97,45,68])
altura=np.array([1.80,1.55,1.75,1.67,1.81])

print(np.stack((peso,altura),axis=0))

[[56.   78.   97.   45.   68.  ]
 [ 1.8   1.55  1.75  1.67  1.81]]


## SPLIT

In [6]:
#split

arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr1,3)
#se genera lista de 3 elementos
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## EJERCICIO CON STACK
Ejercicio crear tres arreglos con aleatorios para los meses de ener (22,42) feb (20,37) marzo(18,30) (7 valores primera semana de cada mes) 
unirlos en uno solo de 3 filas

In [7]:

enero=np.random.randint(22,42,size=7)
febrero=np.random.randint(20,37,size=7)
marzo=np.random.randint(18,30, size=7)

arrstack=np.vstack((enero,febrero,marzo))
arrstack

print(enero)
print("\n",febrero)
print("\n",marzo)

print("\nMax Enero:",np.max(arrstack[0]),"Min Enero",np.min(arrstack[0]))
print("Max Feb:",np.max(arrstack[1]),"Min Feb",np.min(arrstack[1]))
print("Max Mar:",np.max(arrstack[2]),"Min Mar",np.min(arrstack[2]))
print("\n",arrstack)

[41 40 27 38 37 23 34]

 [24 36 32 28 30 22 32]

 [29 23 18 24 27 21 25]

Max Enero: 41 Min Enero 23
Max Feb: 36 Min Feb 22
Max Mar: 29 Min Mar 18

 [[41 40 27 38 37 23 34]
 [24 36 32 28 30 22 32]
 [29 23 18 24 27 21 25]]


## EJERCICIO CON CONCATENATE Y SPLIT
Ejercicio inflacion: Crear dos arreglos denominados primer_sem y segundo_sem. Ambos contienen datos de la inflación mensual del 2022.Utilizar los datos del indec. Luego unirlos en un solo arreglo denominado "anual". Tomar el arreglo creado y dividirlo en trimestres, y mostrar los datos de inflación del primer y el último trimestre

In [8]:

primer_sem=np.array([3.9,4.7,6.7,6.0,5.1,5.3])
segundo_sem=np.array([7.4,7.0,6.2,6.3,4.9,5.1])
anual=np.concatenate((primer_sem,segundo_sem))
trimestre=np.array_split(anual,4)

print("Anual: ",anual)
print("\nTrimestre: ",trimestre)
print("\nInf Primer trimestre: ",trimestre[0])
print("\nInf tercer trimestre: ",trimestre[3])

Anual:  [3.9 4.7 6.7 6.  5.1 5.3 7.4 7.  6.2 6.3 4.9 5.1]

Trimestre:  [array([3.9, 4.7, 6.7]), array([6. , 5.1, 5.3]), array([7.4, 7. , 6.2]), array([6.3, 4.9, 5.1])]

Inf Primer trimestre:  [3.9 4.7 6.7]

Inf tercer trimestre:  [6.3 4.9 5.1]


In [9]:
trimestre2=np.array_split(anual,3)
trimestre2

[array([3.9, 4.7, 6.7, 6. ]),
 array([5.1, 5.3, 7.4, 7. ]),
 array([6.2, 6.3, 4.9, 5.1])]