# CLASE CIENCIA DE DATOS | 12-05 | NUMPY

**IMPORTAMOS LAS LIBRERÍAS**

In [69]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np

# QUE ES UN ARRAY

* **El array (o ndarray) es la estructura que permite acelerar las operaciones matemáticas en Python, sin
la necesidad de recurrir a bucles para operar con todos sus elementos, lo que se llama vectorización.**        


* **Es una estructura multidimensional, por lo que permite representar vectores,     
matrices o arreglos de más dimensiones.**

In [18]:
#crear un array de 1 dimensión
arr1=np.array([1,2,3,4,5])

shape=arr1.shape #me devuelve filas/columnas
ndim=arr1.ndim  #me devuelve la dimension
size=arr1.size
dtype=arr1.dtype
print(f"Cantidad de filas y columnas: {shape}. Dimensión: {ndim}. Cantidad de elementos: {size}. Tipo de datos: {dtype}")

Cantidad de filas y columnas: (5,). Dimensión: 1. Cantidad de elementos: 5. Tipo de datos: int32


In [21]:
#crear un array de 1 lista 
lista=[1,2,3,4,5,6,7]
arr2=np.array(lista)
arr2

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#crear un array de 2 dim
arr3=np.array([[1,2,3],[4,5,6]])
arr3.ndim
print("Cantidad de filas y col",arr3.shape,"Dimensión:",arr3.ndim," Cantidad de elementos: ",arr3.size,"Tipo de datos: ",arr3.dtype)

Cantidad de filas y col (2, 3) Dimensión: 2  Cantidad de elementos:  6 Tipo de datos:  int32


In [32]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr4=np.array([arr3, arr3])
print("Cantidad de filas y col",arr4.shape,"Dimensión:",arr4.ndim," Cantidad de elementos: ",arr4.size,"Tipo de datos: ",arr4.dtype)

Cantidad de filas y col (2, 2, 3) Dimensión: 3  Cantidad de elementos:  12 Tipo de datos:  int32


## Ejercicio matriz de 3 filas y 5 columnas num de 1 al 15

In [48]:
arr5=np.arange(1,16)
arr6=arr5.reshape(3,5)
#arr5=np.arange(1,16).reshape(3,5)

## **RANGO DE VALORES - ARANGE**

In [70]:
a=np.arange(1,16,2)
a
#si agrego 3er paso le indico cada cuanto aumenta

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [73]:
b=np.arange(0,100,25)
b

array([ 0, 25, 50, 75])

## **INDEXING**

In [61]:
a[3]

7

In [63]:
array=np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [66]:
array[:,:2]
#filtro todas la filas y columnas de la cero a la 1

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [67]:
array[2,:]
#filtro ultima fila completa

array([11, 12, 13, 14, 15])

## **FILTRAR CON CONDICIONES**

In [59]:
a[a>10]

array([11, 13, 15])